### ISSUE TITLE
Could not download the job list

### ISSUE THREAD

**Issue by Tim3game-zz** [davidsantos-br/ETS2Sync-Helper-4#11]
Hello,
Today my friend experienced a problem with the application. When he select his DLCs, Profile and Save and click the Sync Jobs he gets this.

<img src=https://cdn.discordapp.com/attachments/302864553425764353/315812684044173312/unknown.png />

He did not have the problem yesterday, but he is suddenly has it today. I never had the problem before.
PS: I'm writing in his place because he does not have a GitHub profile

**Comment by DaviMedrade** [comment]
That error code points to a temporary internet connection issue regarding DNS. Since DNS is often cached by the OS, it might happen even if he can open other websites or connect to TruckersMP, since on earlier access Windows could have cached those DNS results (i.e. “he was connected on multiplayer” doesn't really rule that out).

In any case, since it was a temporary issue, by now it should be working. If it isn't, please reopen this issue, have him try to access the URL below and, if it shows anything other than just the word “current”, report the results.

http://sync.dsantosdev.com/app/check_version?v=5.1.0
