### ISSUE TITLE
Economy reset after sync on ETS2 with v5.2.0

### ISSUE THREAD

**Issue by HaiZenPT** [davidsantos-br/ETS2Sync-Helper-4#13]
Hello, 

I'm having a hard time with the Sync Helper. I saved my game, synced my jobs and after reloading my save game, I'm automatically teleported to the city with the main garage and the ''Game change detected!'' pop-up appears. When I check the freight market, the jobs haven't been synced. So I teleported to another city, saved again, resynced the jobs and reloaded the game and the pop-up appeared again and I'm teleported to the city with the main garage... The problem does not stop repeating.

Please Help!!!

**Comment by HaiZenPT** [comment]
I've got the problem resolved... I had to clear my jobs, reload the save game, save, sync and reload the save game.

**Comment by DaviMedrade** [comment]
If this is still happening, I need to know a bit more.

Which game?
Which DLCs did you have selected?
Are there any error messages in the console?

**Comment by HaiZenPT** [comment]
Greetings David, 

Well, to fix the problem I cleared jobs, reloaded, F7, saved, synced and reloaded. But that worked only once for me... It's not working anymore, unfortunately.

So:

Game: ETS2

Active DLCs: ''Going East!''; ''Scandinavia''; ''Heavy Cargo Pack''; ''High Power Cargo Pack''; ''Metallic Paint Jobs Pack''; ''Michelin Fan Pack''; ''National Window Flags''; ''Rocket League Promo''; ''Cabin Accessories''; ''Spanish Paint Jobs Pack'' and ''Wheel Tuning Pack''.

Errors in the console: As far as I know, no.

David, just so you know, this problem started after I downloaded the new version of the Sync Helper.

(Se quiser falar em português, falamos pelo Steam -> http://steamcommunity.com/id/haizenptone , ou por email -> portista123@live.com.pt)

**Comment by DaviMedrade** [comment]
A log of that situation could be helpful in diagnosing the issue.

1. Start the game (quit and start again if it were already running).
2. Save the game.
3. Sync.
4. Load the save.
5. When the Economy Reset popup (the one saying “Game Change Detected”) appears, close it.
6. Close the game.
7. Attach here the game.log.txt file from Documents\Euro Truck Simulator 2.

Thanks, and sorry for the inconvenience.

I'd rather keep the discussion here, so that if someone else has the same problem they can see we're working on a solution.

(Damn, I wrote this comment right after yours, but apparently I forgot to click to send it.)

**Comment by HaiZenPT** [comment]
Well David, appearently the last few syncs I've made haven't reseted my economy... So can you please close the issue and I might re-open it in the future... when the program starts to reset the economy again. But anyway thank you for the help.

**Comment by DaviMedrade** [comment]
No problem. Thank you.
