### ISSUE TITLE
It economy resets me after syncing with any list 

### ISSUE THREAD

**Issue by RJ56Hours** [davidsantos-br/ETS2Sync-Helper-4#27]
I done and changed nothing since I last played and I did the same thing to sync. But the only difference is that it will economy reset me after my sync. Teleporting me making me unable to access the synced list. I tried re opening and everything. But it just keeps doing the thing

**Comment by DaviMedrade** [comment]
Sorry, that was probably caused by a mistake on my part.

Due to an error I made in the server configuration when version 5.3.1 was released, it was using the testing sync location by mistake. Then, when I made changes to the jobs in that testing location while preparing v5.4.0, v5.3.1 started using those before they were fully ready.

Version 5.4.0 was just released, so please download it and try again. If the problem still happens then please check to make sure you are using the new version and, if so, my mistake was unrelated to it. If that's the case, please reopen this issue so I can investigate.
