### ISSUE TITLE
Error:The system cannot find the file specified 

### ISSUE THREAD

**Issue by nicuiacub** [davidsantos-br/ETS2Sync-Helper-4#28]
Hello,i was having some problems with the ets2 helper sync.I am doing all step right and when i press sync jobs is giving me this  error:The system cannot find the file specified,with the text InternetOpenUrl error 0x00000002.Please can you help me with this problem.(sorry for my bad english,i hope you understand)
Screenshot:
![untitled](https://user-images.githubusercontent.com/35165289/34638792-df98bcae-f2db-11e7-8af4-49b2e44cf540.png)

**Comment by DaviMedrade** [comment]
This is an error reported by Windows. InternetOpenURL is the function that Windows provides to download files. It's weird that it would yield such an error, since it applies to files in the local computer.

Some people have reported this error in other programs, and it seems to be a problem with proxy settings. You can try going to Internet Options (which is in Control Panel and/or the Tools menu of Internet Explorer) → Connections tab → LAN Settings… and making sure that the option “Use a proxy server for your LAN” is unchecked. You can also try unchecking the “Automatically detect settings” option. Then see if you can browse the web using Internet Explorer or if it also yields an error.

Please let me know if it works.

**Comment by nicuiacub** [comment]
Thanks a lot mate,it worked,have a good day.



Pe 9 ian. 2018 03:08, "David Santos" <notifications@github.com> a scris:
