### ISSUE TITLE
Sync not working on ETS2

### ISSUE THREAD

**Issue by Captain-Squareyez** [davidsantos-br/ETS2Sync-Helper-4#37]
Syncs fine on ATS, but cant get it to work at all for ETS2. I tried removing all my mods, nothing. Tried not selecting all my DLC's, nothing. It says its synced, but when i go ingame, it hasnt done anything. 
In the words of Bones McCoy, "It's dead Jim!"

**Comment by Thomasdavid097** [comment]
what is "uset g_save_format" set to? try and make sure that is set to 2 then save the game.

**Comment by Captain-Squareyez** [comment]
Going by what you wrote in the advanced mode, its supposed to be 0. Which is what i have both ATS and ETS2 set to.  With that said, ATS works fine. So, if ATS works like that, why doesnt ETS2?
I asked some guys in discord, and they have the same issue, and they said its broken. Thats when i thought i'd post here.

**Comment by Thomasdavid097** [comment]
I'm not to sure on that maybe a bug, I'm using 2 and that works fine for me

**Comment by Captain-Squareyez** [comment]
so we gonna see a fix for it, or no?

**Comment by Captain-Squareyez** [comment]
do u use it just in multiplayer? or in single player as well as MP?

**Comment by Thomasdavid097** [comment]
I only use it in multiplayer, TruckersMP with my brother/friends.

**Comment by DaviMedrade** [comment]
I don't have a lot of free time lately, but I'll see what I can do. No ETA, though.

It's hard for me to fix a problem I don't have, and it works fine for me, so it must require a specific set of circumstances to trigger the problem. For example, in the past there was an issue where the sync wouldn't work unless the player had the Schwarzmüller DLC (which a lot of people have because it was given away for free at first). Another time, the sync wouldn't work if the person didn't have the Scandinavia DLC, independent of the DLCs selected for syncing.

So, in order to fix this I need to figure out what set of circumstances trigger the problem so I can reproduce them on my computer.

What could help is this: start the game, save, sync, load the synced save, close the game. Then go to `Documents\Euro Truck Simulator 2`, find the game log file, and attach to a comment here.

It would also be useful to know all the DLCs you have.

**Comment by DaviMedrade** [comment]
It's worth noting that syncing on single player won't work, because the synced lists include caravan jobs and those are only available on multiplayer. If you load a synced save in single player mode, I believe that the game will show a “Game Change Detected” message and undo the sync.

**Comment by Captain-Squareyez** [comment]
ahhh, well, if thats the case, then dont worry about it. I'll try it in MP oneday when time permits and im playing ATS or ETS2 again. ATM, im busy building my simulator cockpit, so, im sorry for the late reply :)
No sense in using it in singleplayer really :)
Thanks for the info and help guys
