### ISSUE TITLE
Economy reset after the Heavy Cargo DLC and its accompanying update

### ISSUE THREAD

**Issue by Skippeh** [davidsantos-br/ETS2Sync-Helper-4#9]
When you sync and load, the game says a game change was detected and teleports you to your default company location.

**Comment by JhowDroid** [comment]
@davidsantos-br, Tem previsão para a atualização do sync-helper para a compatibilidade com a nova DLC Heavy Cargo?
@davidsantos-br, You are forecasting to update the sync-helper for compatibility with the new Heavy Cargo DLC?

**Comment by NLD-Farmers** [comment]
@davidsantos-br Same problem here, i hope you will update the Sync Helper. Its the best out there and we use it with our group on daily base! Thanks for your work.

**Comment by Redyx** [comment]
I and three other friends are in the same situation with new update V5. After synchronizing the jobs, the save game detects a change and teleports to the garage, without synchronizing the jobs.

**Comment by derrby** [comment]
Holaaa amigo ayúdanos a sincronizar nos dice que se entregaron las cargas y nos devuelve al garaje sin sincronizar.  te lo agradeceríamos mucho mis amigos y yo quedamos pendientes.

Gracias y saludos

**Comment by DaviMedrade** [comment]
I'll try to update it later today.

**Comment by MeraKz** [comment]
Thank you, we will be waiting for the update

**Comment by NLD-Farmers** [comment]
Thank you @davidsantos-br thats awesome! :)

**Comment by DaviMedrade** [comment]
Working on it now. I have confirmed that even without any heavy cargo jobs there is an economy reset. I re-extracted the game files and regenerated the lists of cities, cargoes, and variants for the base game and each DLC but that didn't fix the problem.

Now I have to figure out if there was a change to the format of the save file, and if not which specific cargo(es) or variant(s) trigger the economy reset and why.

**Comment by DaviMedrade** [comment]
OK, clearing the jobs with ETS2Sync Helper didn't trigger the economy reset, so a change in the save file is unlikely. That's good news and bad news.

Good news is that I don't have to rewrite the part of the program that deals with the save file.

Bad news is that I have to figure out which cargoes/variants cause the issue, and that can take a while. I'll have to do syncs several times until I can isolate the faulty jobs, and I'm using the debug version of the program which takes about ten times as long to sync. In other words, it may take a while.

**Comment by DaviMedrade** [comment]
Odd. It triggered an economy reset even with just a single job. Perhaps the save file did change after all.

**Comment by DaviMedrade** [comment]
Found an issue. The program just replaces some data from the jobs in the save, leaving the other properties as is. One of those properties that the program doesn't change is the truck that will be offered if that job is taken from Quick Jobs instead of the Freight Market.

Apparently in this new version in some cases that property is empty, which means that the program sets up jobs without Quick Jobs trucks attached. When the game sees this, it doesn't like it so it resets the economy.

**Comment by DaviMedrade** [comment]
Yep. It was that. The first half of the issue is fixed. It needs an update in the program, though, so I'll wait to release it when I've implemented heavy cargo support (which is what I'll do now).

![20170515220857_1](https://cloud.githubusercontent.com/assets/39162/26085491/28af1df0-39bb-11e7-84f8-3499b579491c.jpg)

**Comment by GabrielBX** [comment]
então, como que em alguns casos não ouve esse problema? o meu por exemplo continuou sincronizando normalmente.

**Comment by MeraKz** [comment]
Is there any way to have a hotfix, until you have ready the update? Or can give us an approximate time for the update? Thanks, you are amazing . If I'm playing ets2mp, it's thanks to you.

**Comment by DaviMedrade** [comment]
Update released.
